version : "3.4"

services:
  db:
    image:
      postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=username

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db
    ports:
      - "5050:80"
  bot:
    build: 
      context: ./bot/
    volumes:
      - ./bot/:/app/
    restart: always
    depends_on:
        - db
      


volumes:
  pgadmin-data:

#накактит докер композ разобраться с этим файлом и попросить дб, прикрутить сюда пг админ(к докеру)